# reshapeメソッドと配列の形状変更

In [1]:
import numpy as np

In [2]:
a = np.arange(16.)
c = a.reshape(4, -1)
print(a)
print(c)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15.]
[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]
 [12. 13. 14. 15.]]


1次元配列に戻す

In [3]:
c.ravel()

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15.])

In [4]:
c.reshape(-1)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15.])

1次元配列からN行1列行列に変換

In [5]:
b = np.arange(4.)

In [6]:
b.reshape(-1, 1)

array([[0.],
       [1.],
       [2.],
       [3.]])

In [7]:
b[:, None]

array([[0.],
       [1.],
       [2.],
       [3.]])

In [8]:
b[:, np.newaxis]

array([[0.],
       [1.],
       [2.],
       [3.]])

1次元配列を1行N列に変換

In [9]:
b.reshape(1, -1)

array([[0., 1., 2., 3.]])

In [10]:
b

array([0., 1., 2., 3.])

In [11]:
b[np.newaxis, :]

array([[0., 1., 2., 3.]])

In [12]:
b[None, :]

array([[0., 1., 2., 3.]])

もとに戻す

In [13]:
transformed_b = b[None, :]
print(transformed_b)
print(transformed_b.reshape(-1))

[[0. 1. 2. 3.]]
[0. 1. 2. 3.]


# 行列の連結

In [14]:
a = np.arange(6).reshape(2,3)
print(a)
b = np.arange(6, 12).reshape(2,3)
print(b)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


縦方向に連結

In [15]:
np.r_[a,b]

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

横方向に連結

In [16]:
np.c_[a,b]

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

# ブール値を要素に持つ配列を使った抽出

In [17]:
a = np.arange(10, 41, 10)
print(a)
b = np.array([False, True, True, False])
print(b)

[10 20 30 40]
[False  True  True False]


In [18]:
a[b]

array([20, 30])

二次元配列の場合

In [21]:
c = np.arange(3, 9).reshape(2,3)
print(c)
d = np.array([[False, False, True], [False, True, True]])
print(d)

[[3 4 5]
 [6 7 8]]
[[False False  True]
 [False  True  True]]


In [22]:
c[d]

array([5, 7, 8])