# 積和計算の実装パターン

In [15]:
import numpy as np

問1
$$
    \sum_{i=1}^{n}a_{i}x_{i}
$$

In [32]:
np.random.seed(0)
a = np.arange(5)
x = np.zeros(a.shape) + 1
print(a)
print(x)

[0 1 2 3 4]
[1. 1. 1. 1. 1.]


パターン1  
$$
    \boldsymbol{a} = (a_{1}, a_{2}, a_{3}, a_{4}, a_{5}) \\
    \boldsymbol{x} = (x_{1}, x_{2}, x_{3}, x_{4}, x_{5}) \\
    \sum_{i=1}^{n}a_{i}x_{i} = \boldsymbol{a}^{T}\boldsymbol{x}
$$

In [33]:
s1 = np.dot(a, x)
s1

10.0

パターン2  
$$
    \boldsymbol{a} = (a_{1}, a_{2}, a_{3}, a_{4}, a_{5}) \\
    \boldsymbol{x} = (x_{1}, x_{2}, x_{3}, x_{4}, x_{5}) \\
    \begin{align}
        \boldsymbol{tmp} &= \boldsymbol{a} \odot \boldsymbol{x} \\
        &= (a_{1}x_{1}, a_{2}x_{2}, a_{3}x_{3}, a_{4}x_{4}, a_{5}x_{5})
    \end{align} \\
    \sum_{i=1}^{n}a_{i}x_{i} = \boldsymbol{tmp}.sum()
$$

In [34]:
tmp = a * x
print(tmp)
s2 = tmp.sum()
s2

[0. 1. 2. 3. 4.]


10.0

問2
$$
    \sum_{k \neq i,j}a_{k}x_{k} = \sum_{k=1}^{n}a_{k}x_{k} - a_{i}x_{i} - a_{j}x_{j}
$$

In [35]:
s3 = s2 - a[1]*x[1] - a[2]*x[2]
s3

7.0

問3  
$$
    \sum_{i=1}^{n}a_{i}y_{i}\boldsymbol{x}_{i} = a_{1}y_{1}\begin{pmatrix} x_{11}\\x_{21}\\x_{31}\end{pmatrix}
    + a_{2}y_{2}\begin{pmatrix} x_{12}\\x_{22}\\x_{32}\end{pmatrix} + \cdots
    = \begin{pmatrix} \sum_{k=1}^{n}a_{k}y_{k}x_{1k}\\ \sum_{k=1}^{n}a_{k}y_{k}x_{2k} \\ \sum_{k=1}^{n}a_{k}y_{k}x_{3k}\end{pmatrix}
$$

In [36]:
X = np.arange(12).reshape(4,3)
print(X)
a = np.array([1, 1, 1, 1])
y = np.array([2, 2, 2, 2])
print(a*y)
保留

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[2 2 2 2]


NameError: name '保留' is not defined