## 2次元配列と1次元配列の積をとるときは、1次元配列の方向(縦ベクトルか横ベクトルか)を自動的に解釈してくれる

In [1]:
import numpy as np

In [2]:
a = np.arange(9.).reshape(3, 3)
print(a)

[[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]


In [3]:
v = np.arange(1., 4.)
print(v)

[1. 2. 3.]


[3x3]@[1次元配列]

In [4]:
a@v

array([ 8., 26., 44.])

[1次元配列]@[3x3]

In [5]:
v@a

array([24., 30., 36.])

型エラー [3x1]@[3x3]

In [6]:
u = v.reshape(-1, 1)
print(u)
np.dot(u, a)

[[1.]
 [2.]
 [3.]]


ValueError: shapes (3,1) and (3,3) not aligned: 1 (dim 1) != 3 (dim 0)

[3x3]@[3x1]はOK

In [7]:
np.dot(a, u)

array([[ 8.],
       [26.],
       [44.]])

# 配列同士の演算における複雑なブロードキャスト

In [8]:
a = np.arange(12.).reshape(4,3)
a

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.],
       [ 9., 10., 11.]])

In [9]:
b = np.arange(3.).reshape(1,3)
b

array([[0., 1., 2.]])

In [10]:
c = np.arange(4.).reshape(4,1)
c

array([[0.],
       [1.],
       [2.],
       [3.]])

列単位で四則演算

In [11]:
print(a + b)
print()
print(a * b)

[[ 0.  2.  4.]
 [ 3.  5.  7.]
 [ 6.  8. 10.]
 [ 9. 11. 13.]]

[[ 0.  1.  4.]
 [ 0.  4. 10.]
 [ 0.  7. 16.]
 [ 0. 10. 22.]]


行単位で四則演算

In [12]:
print(a + c)
print()
print(a * c)

[[ 0.  1.  2.]
 [ 4.  5.  6.]
 [ 8.  9. 10.]
 [12. 13. 14.]]

[[ 0.  0.  0.]
 [ 3.  4.  5.]
 [12. 14. 16.]
 [27. 30. 33.]]


[1x3]□[3x1]の演算

In [13]:
print(b)
print(c)
print()
print(b-c)
print(b+c)
print(b*c)

[[0. 1. 2.]]
[[0.]
 [1.]
 [2.]
 [3.]]

[[ 0.  1.  2.]
 [-1.  0.  1.]
 [-2. -1.  0.]
 [-3. -2. -1.]]
[[0. 1. 2.]
 [1. 2. 3.]
 [2. 3. 4.]
 [3. 4. 5.]]
[[0. 0. 0.]
 [0. 1. 2.]
 [0. 2. 4.]
 [0. 3. 6.]]


なるべくfor文よりもnumpyのブロードキャストを活用するほうが計算効率が高い

# 終わり