# 疎行列の計算

lil_matrix型の疎行列を作成

In [1]:
from scipy import sparse
a = sparse.lil_matrix((4,5))

In [2]:
a[0,1] = 1
a[1,1] = 2
a[2,2] = 3
a[3,4] = 4

通常の行列に変換

In [3]:
a.toarray()

array([[0., 1., 0., 0., 0.],
       [0., 2., 0., 0., 0.],
       [0., 0., 3., 0., 0.],
       [0., 0., 0., 0., 4.]])

In [4]:
b = sparse.lil_matrix((5,4))

In [5]:
b[0,2] = 1
b[1,2] = 2
b[2,3] = 3
b[3,3] = 4

In [6]:
b.toarray()

array([[0., 0., 1., 0.],
       [0., 0., 2., 0.],
       [0., 0., 0., 3.],
       [0., 0., 0., 4.],
       [0., 0., 0., 0.]])

疎行列の積

In [7]:
c = a.dot(b)
print(c)
c.toarray()

  (0, 2)	2.0
  (1, 2)	4.0
  (2, 3)	9.0


array([[0., 0., 2., 0.],
       [0., 0., 4., 0.],
       [0., 0., 0., 9.],
       [0., 0., 0., 0.]])

# 疎行列による計算をする場合、csr_matrix型またはcsc_matrix型に変換して計算

## csr_matrix型に変換


行の取り出しが早い

In [10]:
a1 = a.tocsr() # csr_matrix
print(a1.toarray())
b1 = b.tocsr()
print(b1.toarray())

[[0. 1. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 0. 4.]]
[[0. 0. 1. 0.]
 [0. 0. 2. 0.]
 [0. 0. 0. 3.]
 [0. 0. 0. 4.]
 [0. 0. 0. 0.]]


In [12]:
c1 = a1.dot(b1)
c1.toarray()

array([[0., 0., 2., 0.],
       [0., 0., 4., 0.],
       [0., 0., 0., 9.],
       [0., 0., 0., 0.]])

## csc_matrix型に変換

列の取り出しが早い

In [15]:
a2 = a.tocsc() # csc_matrix
print(a2.toarray())
b2 = b.tocsc()
print(b2.toarray())

[[0. 1. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 0. 4.]]
[[0. 0. 1. 0.]
 [0. 0. 2. 0.]
 [0. 0. 0. 3.]
 [0. 0. 0. 4.]
 [0. 0. 0. 0.]]


In [ ]:
c2 = a2.dot(b2)
c2.toarray()

## lil_matrixでも計算はできるが、速度面でcsr_matrixとcsc_matrixの方が勝っている
### ただし、csr_matrixとcsc_matrixは行列の要素に逐次値を設定することができない。
以下、使い方
1. lil_matrix型の変数を用意して、各要素に値を設定する
2. 設定されたlil_matrixをcsr_matrixまたはcsc_matrixに変換する
3. 変換された疎行列について計算をする

In [16]:
a = sparse.lil_matrix((4,4))
a[0,1] = 1
a[1,2] = 2
a[2,3] = 3
a[3,3] = 4
a1 = a.tocsr()
a2 = a.tocsc()

In [17]:
type(a1)

scipy.sparse.csr.csr_matrix

In [18]:
type(a2)

scipy.sparse.csc.csc_matrix

csr_matrix型はgetrowメソッドで効率よく行を抽出する　

In [24]:
print(a1.toarray())
b1 = a1.getrow(1)
b1

[[0. 1. 0. 0.]
 [0. 0. 2. 0.]
 [0. 0. 0. 3.]
 [0. 0. 0. 4.]]


<1x4 sparse matrix of type '<class 'numpy.float64'>'
	with 1 stored elements in Compressed Sparse Row format>

In [21]:
b1.toarray()

array([[0., 0., 2., 0.]])

csc_matrix型はgetcolメソッドで効率よく列を抽出する

In [25]:
print(a2.toarray())
b2 = a2.getcol(1)
b2

[[0. 1. 0. 0.]
 [0. 0. 2. 0.]
 [0. 0. 0. 3.]
 [0. 0. 0. 4.]]


<4x1 sparse matrix of type '<class 'numpy.float64'>'
	with 1 stored elements in Compressed Sparse Column format>

In [26]:
b2.toarray()

array([[1.],
       [0.],
       [0.],
       [0.]])

In [27]:
print(type(b1.T))
print(type(b2.T))

<class 'scipy.sparse.csc.csc_matrix'>
<class 'scipy.sparse.csr.csr_matrix'>


# 終わり