In [1]:
import numpy as np
import scipy as sp

# Numpy/SciPyによる線形代数

### 逆行列を求める(通常)

In [3]:
from scipy.linalg import inv
import numpy as np
a = np.array([[3,1,1], [1,2,1], [0,-1,1]])

In [4]:
np.linalg.inv(a)

array([[ 0.42857143, -0.28571429, -0.14285714],
       [-0.14285714,  0.42857143, -0.28571429],
       [-0.14285714,  0.42857143,  0.71428571]])

### 逆行列を求める(高速かつ安定)

1次方程式を解く関数np.linang.solve

In [6]:
a = np.array([[3,1,1], [1,2,1], [0,-1,1]])
b = np.array([1,2,3])
np.linalg.solve(a,b)

array([-0.57142857, -0.14285714,  2.85714286])

逆行列を求めるアルゴリズムと1次方程式を解くアルゴリズムは別で、1次方程式を解く方が高速かつ数値的安定

# LU分解によって高速かつ安定して1次方程式の解を求める

### 1次方程式 Ax=b
### LU分解     A=PLU
### LU分解を活用した1次方程式 PLUx=b
こっちのほうが速く、効率が良い
1. Pz = b
2. Ly = z
3. Ux = y


In [8]:
a = np.array([[3,1,1], [1,2,1], [0,-1,1]])
b = np.array([1,2,3])

In [9]:
from scipy import linalg
lu, p = linalg.lu_factor(a)
linalg.lu_solve((lu,p), b)

array([-0.57142857, -0.14285714,  2.85714286])

# 終わり