In [1]:
import numpy as np

# ブール値を要素に持つ配列を使った抽出

In [2]:
a = np.arange(10, 41, 10)
print(a)
b = np.array([False, True, True, False])
print(b)

[10 20 30 40]
[False  True  True False]


In [3]:
a[b]

array([20, 30])

2次元配列の場合

In [4]:
c = np.arange(3, 9).reshape(2,3)
print(c)
d = np.array([[False, False, True], [False, True, True]])
print(d)

[[3 4 5]
 [6 7 8]]
[[False False  True]
 [False  True  True]]


In [5]:
c[d]

array([5, 7, 8])

# 条件指定による要素の抽出

In [6]:
a = np.arange(10)
print(a)
a[a>5]

[0 1 2 3 4 5 6 7 8 9]


array([6, 7, 8, 9])

In [7]:
a[(a>=3)&(a<6)]

array([3, 4, 5])

In [8]:
a[(a<2)|(a>7)]

array([0, 1, 8, 9])

In [9]:
a[a%3 !=0]

array([1, 2, 4, 5, 7, 8])

# 終わり